# tomcat
server:
  port: 8002
spring:
  application:
    name: maongo-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name} 
# backup datasource
mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: mango   
      
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      
   