# tomcat
server:
  port: 8003
spring:
  application:
    name: maongo-backup
  boot:
    admin:
      client:
        url: "http://localhost:8004"
        
# backup datasource
mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: mango   
      
# Spring Boot Admin
management:
  endpoints:
    web:
      exposure:
        include: "*"