###服务端口号
server:
  port: 8004
spring:
  application:
    name: consul-member
####consul注册中心地址
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:  ##表示服务地址 服务所在主机ip
        hostname: 127.0.0.1
##默认情况下 服务注册到注册中心上的地址是随机生成的英文名字